---
title: "Favaro et al. (2014) Paper Summary"
author: "Cole Brookson, Alex Davis"
date: "10/13/2021"
output:
    pdf_document
---

## Broad Questions

1) What are the barriers to implementing this framework (Two-Eyed Seeing) as western scientists

2) Why is it your job to do Two-Eyed Seeing? 

3) As western scientists, why do we have to implement this framework


## Changing Viewpoints

This discussion helped the class better understand that Two-Eyed Seeing is not "incorporation" or "addition" of indigenous knowledge to western science or our work (as this is assimilative), but rather an approach to co-developing research with indigenous communities. It helped us understand that true Two-Eyed Seeing involves long term relationships with indigenous communities that lead to mutual formation of questions. These questions are investigated with indigenous and western science methodologies, and the long term relationships persist. 


## Connections




## Epistomology





## How Science Happens


